--create table audit (id bigint generated by default as identity, action varchar(10), primary key (id))
--create table bank (id bigint generated by default as identity, name varchar(75), primary key (id))
--create table bank_audit (bank_id bigint not null, audit_id bigint not null unique, primary key (bank_id, audit_id))
--create table person (id bigint generated by default as identity, first_name varchar(30), last_name varchar(30), primary key (id))
--create table person_audit (person_id bigint not null, audit_id bigint not null unique, primary key (person_id, audit_id))
--alter table bank_audit add constraint bank_audit_bank_id foreign key (bank_id) references bank
--alter table bank_audit add constraint bank_audit_audit_id foreign key (audit_id) references audit
--alter table person_audit add constraint person_audit_person_id foreign key (person_id) references person
--alter table person_audit add constraint person_audit_audit_id foreign key (audit_id) references audit

insert into person (id, first_name, last_name) values (1, 'bubo', 'lee')
insert into audit (id, action) values (1, 'saved')
insert into person_audit (person_id, audit_id) values (1, 1)

insert into bank (id, name) values (1, 'very special bank')
insert into audit (id, action) values (2, 'inserted')
insert into bank_audit (bank_id, audit_id) values (1, 2)